version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: chat_app_db
    restart: always
    environment:
      MYSQL_DATABASE: chat_app
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_app_server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=chatuser
      - DB_PASSWORD=chatpassword
      - DB_NAME=chat_app
      - DB_PORT=3306
      - JWT_SECRET=your_jwt_secret_key_here
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data: